import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export async function exportToPDF(messages, user, activeTab = 'Chat') {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
  const userName = user?.name || 'Authorized Officer';
  const userRole = user?.role || 'Investigator';
  const userId = user?.id || 'KSP-UID-UNKNOWN';

  // Margins & dimensions
  const margin = 20;
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);
  let y = 35; // Cursor Y position

  // Draw Header Border & Emblems
  const drawHeader = (pageNum) => {
    doc.setDrawColor(27, 42, 74); // Navy
    doc.setLineWidth(1);
    doc.line(margin, 10, pageWidth - margin, 10);
    doc.line(margin, 28, pageWidth - margin, 28);

    // KSP Emblem Placeholder Gold Box
    doc.setFillColor(200, 146, 42); // Gold #C8922A
    doc.rect(margin + 2, 12, 12, 12, 'F');
    doc.setTextColor(27, 42, 74);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(8);
    doc.text('KSP', margin + 3.5, 20);

    // Title Block
    doc.setTextColor(27, 42, 74);
    doc.setFontSize(14);
    doc.text('KARNATAKA STATE POLICE', margin + 20, 18);
    doc.setFontSize(9);
    doc.setFont('Helvetica', 'normal');
    doc.text('CRIME INTELLIGENCE Platform — CONFIDENTIAL REPORT', margin + 20, 23);

    // Page Number
    doc.setFontSize(8);
    doc.setTextColor(100, 110, 120);
    doc.text(`Page ${pageNum}`, pageWidth - margin - 15, 20);
  };

  // Draw Footer on each page
  const drawFooter = () => {
    doc.setDrawColor(209, 213, 219); // Light border
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

    doc.setFontSize(8);
    doc.setFont('Helvetica', 'bold');
    doc.setTextColor(155, 28, 28); // Dark Red Danger color
    doc.text('CLASSIFICATION: FOR INTERNAL USE ONLY — SHIELD LEVEL 3', margin, pageHeight - 10);
    
    doc.setFont('Helvetica', 'normal');
    doc.setTextColor(100, 110, 120);
    doc.text('Generated by KAVERI Platform', pageWidth - margin - 45, pageHeight - 10);
  };

  // Setup first page
  drawHeader(1);
  drawFooter();

  // Document Metadata Block
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(27, 42, 74);
  doc.text('REPORT DETAILS:', margin, y);
  y += 6;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(26, 26, 46);
  
  const details = [
    `Generated By: ${userName} (${userId})`,
    `Officer Role: ${userRole}`,
    `Date/Time: ${timestamp}`,
    `Subject Area: KSP Intelligence Dossier`
  ];

  details.forEach(detail => {
    doc.text(detail, margin, y);
    y += 5;
  });

  y += 5;
  doc.setDrawColor(209, 213, 219);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Add conversation content
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(27, 42, 74);
  doc.text('CONVERSATION CHRONOLOGY & INTELLIGENCE INPUTS:', margin, y);
  y += 10;

  let pageNum = 1;

  for (let i = 0; i < messages.length; i++) {
    const msg = messages[i];
    
    // Check page overflow
    if (y > pageHeight - 35) {
      doc.addPage();
      pageNum++;
      drawHeader(pageNum);
      drawFooter();
      y = 35;
    }

    const speaker = msg.role === 'user' ? 'USER / INVESTIGATOR' : 'KAVERI ASSISTANT';
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(9);
    const color = msg.role === 'user' ? [27, 42, 74] : [200, 146, 42];
    doc.setTextColor(color[0], color[1], color[2]); // Navy vs Gold
    doc.text(speaker, margin, y);
    y += 5;

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(26, 26, 46);

    // Split text to fit width
    const textLines = doc.splitTextToSize(msg.text, contentWidth);
    
    textLines.forEach(line => {
      if (y > pageHeight - 25) {
        doc.addPage();
        pageNum++;
        drawHeader(pageNum);
        drawFooter();
        y = 35;
      }
      doc.text(line, margin, y);
      y += 5;
    });

    if (msg.citations && msg.citations.length > 0) {
      y += 2;
      doc.setFont('Helvetica', 'italic');
      doc.setFontSize(8.5);
      doc.setTextColor(74, 85, 104);
      doc.text(`References: ${msg.citations.join(', ')}`, margin, y);
      y += 5;
    }

    y += 6; // Margin between bubbles
  }

  // If dashboard chart or network graph is visible, let's grab it via canvas snapshot and insert
  const snapshotEl = document.querySelector('.graph-container') || document.querySelector('.recharts-wrapper');
  if (snapshotEl) {
    try {
      console.log("Found interactive visual element. Capturing canvas snapshot...");
      
      // Add page for snapshot
      doc.addPage();
      pageNum++;
      drawHeader(pageNum);
      drawFooter();
      y = 35;

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(27, 42, 74);
      doc.text('VISUALIZATION RECORD (SNAPSHOT):', margin, y);
      y += 10;

      const canvas = await html2canvas(snapshotEl, { scale: 1.5 });
      const imgData = canvas.toDataURL('image/jpeg', 0.85);
      
      // Map canvas aspect ratio to fits in page width (contentWidth = 170mm)
      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      doc.addImage(imgData, 'JPEG', margin, y, imgWidth, imgHeight);
      y += imgHeight + 10;
    } catch (err) {
      console.error("Failed to capture visualization canvas:", err);
    }
  }

  // Save PDF
  const filename = `KSP_Intelligence_Report_${Date.now()}.pdf`;
  doc.save(filename);
}
